// Get all users
GET http://localhost:3001/api/users
###
// Get user by Id
GET http://localhost:3001/api/user
Content-Type: application/json

{
  "_id": "6302b6008adaa56bd90b9440" 
}
###
//Create User
POST http://localhost:3001/api/user
Content-Type: application/json

{
  "username": "PhilSwift",
  "email": "patchitphil@flex.org"
}
###
//Update user 
PUT  http://localhost:3001/api/user
Content-Type: application/json

{
  "_id": "6302b6008adaa56bd90b9440",
  "username": "Palmer",
  "email": "pfunkaloo13@gmail.com"
}
###
//Deleter use by id
DELETE   http://localhost:3001/api/user/6302b65d886ed0aa0e837b54
Content-Type: application/json
###
//Add friend to user
POST http://localhost:3001/api/user/6302b6008adaa56bd90b9440/friends/6302b62f56934a9cebf36e39
###
//Delete friend from user
DELETE http://localhost:3001/api/user/6302b6008adaa56bd90b9440/friends/6302b62f56934a9cebf36e39
###
//Get all thoughts
GET http://localhost:3001/api/thoughts
###
// get thought by id
GET http://localhost:3001/api/thought
Content-Type: application/json

{
  "_id": "6302b72e886ed0aa0e837b64" 
}
###
//Create thought
POST http://localhost:3001/api/thought
Content-Type: application/json

{
  "thoughtText": "ANOTHEEEEER",
  "username": "Palmer"
}
###
//Update thought by id
PUT  http://localhost:3001/api/thought
Content-Type: application/json

{
  "_id": "6302b72e886ed0aa0e837b64",
  "thoughtText": "Yeah im a really good programmer",
  "username": "Palmer"
}
###
//Delete thought
DELETE   http://localhost:3001/api/thoughts/6302bb96deb3745c0332386d


###
//Add reaction 
POST  http://localhost:3001/api/thoughts/6302b72e886ed0aa0e837b64/reactions
Content-Type: application/json

{
  "reactionBody": "OMG that is so cool",
  "username": "Mushroom"
}

###
//Delete reaction 
DELETE   http://localhost:3001/api/thoughts/6302b72e886ed0aa0e837b64/reactions
Content-Type: application/json

{
  "reactionId": "6302bbcedeb3745c03323872"
}
